---
title: "Week 14"
author: "Evan Wu"
output: 
  html_document:
    code_folding:
      hide
---

<br>

#### Code Background

Looking at whiff data for left-handed pitchers (35 pitchers from 2022, all with
1842+ seasonal pitches). 

<br>

#### Libraries
```{r Libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(knitr)
library(ranger)
library(glmnet)
library(forcats)
library(olsrr)
library(Metrics)
library(mgcv)
library(caret)
```


``` {r Functions, }
# Geom Zone (Jackie's) ####

geom_zone <- function(top = 11/3, bottom = 3/2, linecolor = "black"){
  geom_rect(xmin = -.7083, xmax = .7083, ymin = bottom, ymax = top,
            alpha = 0, color = linecolor, linewidth = 0.75)
}

# c(0, 0, -.25, -.5, -.25))

geom_plate <- function(pov = "pitcher"){
   df <- case_when(
     pov == "pitcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, .25, .5, .25)),
     pov == "catcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, -.25, -.5, -.25))
   )
  
   g <- geom_polygon(data = df, aes(x = x, y = y), fill = "white", color = "black", linewidth = 1.25)
  g
}
```

#### Data
```{r Data, message = FALSE, warning = FALSE}

all <- read_csv("CSVs/all_pitches.csv") %>% 
  select(-...1) %>% 
  mutate(wOBAr = case_when(
    woba >= 0.370 ~ 6,
    woba >= 0.340 ~ 5,
    woba >= 0.310 ~ 4,
    woba >= 0.280 ~ 3,
    woba >= 0.250 ~ 2,
    woba >= 0.220 ~ 1)) %>% 
  mutate(wOBAr = as.factor(wOBAr))

```

```{r, warning = FALSE, message = FALSE}
whiff_comparison <- all %>% 
  filter(pitch_speed > 95.5, pitch_speed < 96,
         pitch_type == "FF",
         player_id == c("434378", "450203"))

ff_averages <- all %>% 
  filter(pitch_type == "FF",
         !is.na(release_spin_rate)) %>% 
  group_by(player_name) %>% 
  summarize(Whiff = mean(whiff),
            Speed = mean(pitch_speed),
            "Spin Rate" = mean(release_spin_rate),
            "X Break" = mean(pfx_x),
           "Z Break" = mean(pfx_z))

RHP_sample <- ff_averages %>% 
  filter(between(Speed, 95.5, 96.5),
         between(`Spin Rate`, 2300, 2400),
         between(`X Break`, -0.6, -0.4)) %>% 
  mutate(pitch_hand = "R")

LHP_sample <- ff_averages %>% 
  filter(between(Speed, 91.5, 92.5),
         between(`Spin Rate`, 2100, 2200),
         between(`X Break`, 0.5, 0.7)) %>% 
  mutate(pitch_hand = "L")

RHP <- all %>% 
  filter(player_name == c("Woodruff, Brandon", "Montas, Frankie"))

LHP <- all %>% 
  filter(player_name == c("Corbin, Patrick", "Bubic, Kris"))

sample <- rbind(RHP, LHP) %>% 
  as.data.frame()

RHP %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = -plate_x, y = plate_z, 
             color = player_name)) +
  geom_zone() +
  geom_point(alpha = 0.5) +
  coord_fixed() +
  facet_wrap(~whiff) +
  labs(color = "Pitcher",
       title = "Fastball Location")

RHP %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = -pfx_x, y = pfx_z, 
             color = player_name)) +
  geom_point(alpha = 0.5) +
  coord_fixed() +
  facet_wrap(~whiff) +
  labs(color = "Pitcher",
       title = "Fastball Movement")

RHP_avg <- RHP %>% 
  group_by(player_name,
           pitch_name) %>% 
  filter(!is.na(release_spin_rate)) %>% 
  summarize(Pitches = n(),
            Whiff = mean(whiff),
            Speed = mean(pitch_speed),
            "Spin Rate" = mean(release_spin_rate),
            "X Break" = mean(pfx_x),
           "Z Break" = mean(pfx_z))

RHP_avg %>% 
  ggplot(aes(x = -`X Break`, y = `Z Break`,
             color = Whiff, shape = player_name)) +
  geom_hline(yintercept = 0, size = 0.5, color = "black") +
  geom_vline(xintercept = 0, size = 0.5, color = "black") +
  coord_fixed() +
  geom_point() +
  scale_color_gradient(low = "yellow2", high = "green") +
  facet_wrap(~ pitch_name)


LHP %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = -plate_x, y = plate_z, 
             color = player_name)) +
  geom_zone() +
  geom_point(alpha = 0.5) +
  coord_fixed() +
  facet_wrap(~whiff) +
  labs(color = "Pitcher",
       title = "Fastball Location")

LHP %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = -pfx_x, y = pfx_z, 
             color = player_name)) +
  geom_point(alpha = 0.5) +
  coord_fixed() +
  facet_wrap(~whiff) +
  labs(color = "Pitcher",
       title = "Fastball Movement")

LHP_avg <- LHP %>% 
  group_by(player_name,
           pitch_name) %>% 
  filter(!is.na(release_spin_rate)) %>% 
  summarize(Pitches = n(),
            Whiff = mean(whiff),
            Speed = mean(pitch_speed),
            "Spin Rate" = mean(release_spin_rate),
            "X Break" = mean(pfx_x),
           "Z Break" = mean(pfx_z))

LHP_avg %>% 
  ggplot(aes(x = -`X Break`, y = `Z Break`,
             color = Whiff, shape = player_name)) +
  geom_hline(yintercept = 0, size = 0.5, color = "black") +
  geom_vline(xintercept = 0, size = 0.5, color = "black") +
  coord_fixed() +
  geom_point() +
  scale_color_gradient(low = "yellow2", high = "green") +
  facet_wrap(~ pitch_name)
```

```{r}
test <- all %>% 
  group_by(player_name) %>% 
  summarize(woba = mean(woba),
            whiff = mean(whiff))

X2022_stats <- read_csv("Pitcher Seasonal Data/2022_stats.csv")

stats <- X2022_stats %>% 
  mutate(player_name = `last_name, first_name`) %>% 
  left_join(test, by = "player_name") %>% 
  filter(!is.na(whiff))

stats %>% 
  ggplot(aes(x = whiff, y = k_percent/100)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(x = "Whiff Rate",
       y = "Strikeout Percentage",
       title = "Strikeout Percentage vs. Whiff Rate",
       caption = "Data from Baseball Savant",
       subtitle = "Data: 2022 Seasonal Stats for Pitchers with 1800+ Pitches") +
  scale_x_continuous(labels = scales::percent) +
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

cor(stats$p_era, stats$k_percent)
```

```{r Whiff Rate Predictions, warning = FALSE, message = FALSE}

# Speed
all %>% 
  mutate(speed_rounded = round(pitch_speed, 1)) %>% 
  group_by(pitch_name, speed_rounded) %>% 
  summarize(whiff_rate = mean(whiff), pitches = n()) %>% 
  filter(pitches >= 10) %>% 
  ggplot(aes(x = speed_rounded, y = whiff_rate)) +
  geom_point(aes(color = whiff_rate),
             size = 0.5, show.legend = FALSE) +
  geom_smooth(se = FALSE, size = 0.5) +
  facet_wrap(~ pitch_name) +
  scale_color_gradient(low = "skyblue", high = "firebrick") +
  labs(x = "Pitch Speed",
       y = "Whiff Rate",
       title = "Whiff Rate vs. Pitch Speed",
       caption = "Shows speeds to one decimal with at least 10 pitches/observations.") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))


# Spin
all %>% 
  mutate(spin_rounded = round(release_spin_rate, -1)) %>% 
  group_by(pitch_name, spin_rounded) %>% 
  summarize(whiff_rate = mean(whiff), pitches = n()) %>% 
  filter(pitches >= 10) %>% 
  ggplot(aes(x = spin_rounded, y = whiff_rate)) +
  geom_point(aes(color = whiff_rate),
             size = 0.5, show.legend = FALSE) +
  geom_smooth(se = FALSE, size = 0.5) +
  facet_wrap(~ pitch_name) +
  scale_color_gradient(low = "skyblue", high = "firebrick") +
  labs(x = "Spin Rate (rpm)",
       y = "Whiff Rate",
       title = "Whiff Rate vs. Spin Rate",
       caption = "Shows spin rate groups rounded to the tens place with at least 10 pitches/observations.") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))


# Horizontal Movement
all %>% 
  mutate(movement_rounded = round(pfx_x*12*2)/2) %>% 
  group_by(pitch_name, movement_rounded) %>% 
  summarize(whiff_rate = mean(whiff), pitches = n()) %>% 
  filter(pitches >= 10) %>% 
  ggplot(aes(x = movement_rounded, y = whiff_rate)) +
  geom_point(aes(color = whiff_rate),
             size = 0.5, show.legend = FALSE) +
  geom_smooth(se = FALSE, size = 0.5) +
  facet_wrap(~ pitch_name) +
  scale_color_gradient(low = "skyblue", high = "firebrick") +
  labs(x = "Horizontal Break (in.)",
       y = "Whiff Rate",
       title = "Whiff Rate vs. Horizontal Break (in.)",
       caption = "Shows horizontalpitch movement groups rounded to the nearest
       0.5 with at least 10 pitches/observations.") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))



# Vertical Movement
all %>% 
  mutate(movement_rounded = round(pfx_z*12*2)/2) %>% 
  group_by(pitch_name, movement_rounded) %>% 
  summarize(whiff_rate = mean(whiff), pitches = n()) %>% 
  filter(pitches >= 10) %>% 
  ggplot(aes(x = movement_rounded, y = whiff_rate)) +
  geom_point(aes(color = whiff_rate),
             size = 0.5, show.legend = FALSE) +
  geom_smooth(se = FALSE, size = 0.5) +
  facet_wrap(~ pitch_name) +
  scale_color_gradient(low = "skyblue", high = "firebrick") +
  labs(x = "Vertical Break (in.)",
       y = "Whiff Rate",
       title = "Whiff Rate vs. Vertical Break (in.)",
       caption = "Shows vertical pitch movement groups rounded to the nearest
       0.5 with at least 10 pitches/observations.") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```

