---
title: "Week 3"
author: "Evan Wu"
output: 
  html_document:
    code_folding:
      hide
---

<br>

#### Code Background

Looking at whiff data for right-handed pitchers (from 2022, 85 pitchers with
1842+ seasonal pitches). 

<br>

#### Libraries
```{r Libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
library(glmnet)
library(patchwork)
library(olsrr)
```


``` {r Functions, }
# Geom Zone (Jackie's) ####

geom_zone <- function(top = 11/3, bottom = 3/2, linecolor = "black"){
  geom_rect(xmin = -.7083, xmax = .7083, ymin = bottom, ymax = top,
            alpha = 0, color = linecolor, linewidth = 0.75)
}

# c(0, 0, -.25, -.5, -.25))

geom_plate <- function(pov = "pitcher"){
   df <- case_when(
     pov == "pitcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, .25, .5, .25)),
     pov == "catcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, -.25, -.5, -.25))
   )
  
   g <- geom_polygon(data = df, aes(x = x, y = y), fill = "white", color = "black", linewidth = 1.25)
  g
}
```

#### Data
```{r Data, message = FALSE, warning = FALSE}

rhp <- read_csv("CSVs/rhp_pitches.csv") %>% 
  select(-...1) %>% 
  filter(!is.na(pfx_z)) %>% 
  mutate(distance_sweet = sqrt(((plate_x - 0.85)^2)+((plate_z - 1.55)^2))) %>% 
  mutate(zone = case_when(distance < 2 ~ zone,
                          distance >= 2 & plate_z > (sz_top + sz_bot)/2 ~ 16,
                          distance >= 2 & plate_z <= (sz_top + sz_bot)/2 ~ 17)) %>% 
  mutate(ab_id = paste0(game_date, "_", player_id, "_", at_bat_number),
         prev_ab_id = lead(ab_id, 1)) %>% 
  mutate(prev_pitch = ifelse(ab_id == prev_ab_id, lead(pitch_type, 1), NA)) %>% 
  select(-ab_id, -prev_ab_id) %>% 
  mutate(prev_pitch = case_when(prev_pitch  %in% c("FF", "FC", "SI") ~ "Fastball",
                                prev_pitch %in% c("SL", "CU", "KC", 
                                                  "SV", "ST", "CS") ~ "Breaking Ball",
                                prev_pitch  %in% c("CH", "FS") ~ "Off Speed")) %>% 
  mutate(zone = as.factor(zone))

rhp <- rhp %>% 
  mutate(prev_pitch = ifelse(is.na(prev_pitch), "None", prev_pitch)) %>% 
  mutate(Count = paste0(balls, "-", strikes)) %>% 
  mutate(Count = as.factor(Count))

sliders <- rhp %>% 
  filter(hitter == "R") %>% 
  filter(pitch_type == "SL") %>% 
  mutate(count = paste0(balls, "_", strikes),
         prev_pitch = as.factor(prev_pitch)) %>% 
  mutate(prev_pitch_ff = ifelse(prev_pitch == "FF", 1, 0))
  
fastballs <- rhp %>% 
  filter(hitter == "R") %>% 
  filter(pitch_type == fb_type) %>% 
  mutate(count = paste0(balls, "_", strikes),
         prev_pitch = as.factor(prev_pitch))

```

#### Slider Initial Model

```{r Slider Init Model, message = FALSE}
# Initial Model
sl_model_all <- glm(whiff ~ pitch_speed + pfx_x + pfx_z + plate_x + plate_z + zone +
              count + pfx_total + speed_change + break_change + distance + 
                prev_pitch + speed_fb_diff + pfx_x_fb_diff + pfx_z_fb_diff +
                speed_change^2 + break_change^2 + distance^2 + 
                I(plate_x^2) + I(plate_z^2) +
                speed_fb_diff^2 + pfx_x_fb_diff^2 + pfx_z_fb_diff^2,
              data = sliders, family = binomial)

# Model Evaluation
summary(sl_model_all)
```

#### Slider Refined Model & Predictions

```{r Slider Refined Model, message = FALSE}
sl_model <- glm(whiff ~ pitch_speed + pfx_x + pfx_z + plate_x + plate_z + zone +
              pfx_total + speed_change + break_change + distance + 
                prev_pitch + speed_fb_diff + I(plate_x^2) + I(plate_z^2),
              data = sliders, family = binomial)
sl_model %>% summary

# Model Predictions
sl_preds <- sliders %>% 
  mutate(prediction_log = predict(sl_model, sliders),
         prediction = 1 / (1 + exp(-prediction_log)),
         rounded_pred = case_when(
           prediction >= 0.5 ~ 1,
           prediction < 0.5 ~ 0
         )) %>% 
  filter(!is.na(prediction))

sl_preds %>% 
  mutate(prediction = round(prediction, 2)) %>% 
  group_by(prediction) %>% 
  summarize(n = n(), whiff_rate = mean(whiff)) %>% 
  as.data.frame() %>% 
  ggplot(aes(x = prediction, y = whiff_rate)) +
  geom_point(aes(size = n)) + # size of bin shown on graph
  coord_fixed() +
  geom_smooth(se = FALSE) +
  labs(y = "observed whiff proportion",
       x = "projected % whiff chance",
       title = "Slider Whiff Model Prediction",
       subtitle = "Whiff proportion by predicted whiff value",
       caption = "Whiff predictions have a 1% bin width")
```

#### Fastball Initial Model

```{r Fastball Init Model, message = FALSE}
# Initial Model
fb_model_all <- glm(whiff ~ pitch_speed + pfx_x + pfx_z + plate_x + plate_z + zone +
              count + pfx_total + speed_change + break_change + distance + 
                prev_pitch + pitch_type + I(plate_x^2) + I(plate_z^2) +
                speed_change^2 + break_change^2 + distance^2,
              data = fastballs, family = binomial)

# Model Evaluation
summary(fb_model_all)
```

#### Fastball Refined Model & Predictions

```{r Fastball Refined Model, message = FALSE}
fb_model <- glm(whiff ~ pitch_speed + pfx_x + pfx_z + plate_x + plate_z + zone +
              pfx_total + speed_change + break_change + 
                pitch_type + I(plate_x^2) + I(plate_z^2),
              data = fastballs, family = binomial)
fb_model %>% summary

# Model Predictions
fb_preds <- fastballs %>% 
  mutate(prediction_log = predict(fb_model, fastballs),
         prediction = 1 / (1 + exp(-prediction_log)),
         rounded_pred = case_when(
           prediction >= 0.5 ~ 1,
           prediction < 0.5 ~ 0
         )) %>% 
  filter(!is.na(prediction))

fb_preds %>% 
  mutate(prediction = round(prediction, 2)) %>% 
  group_by(prediction) %>% 
  summarize(n = n(), whiff_rate = mean(whiff)) %>% 
  as.data.frame() %>% 
  ggplot(aes(x = prediction, y = whiff_rate)) +
  geom_point(aes(size = n)) + # size of bin shown on graph
  coord_fixed() +
  geom_smooth(se = FALSE) +
  labs(y = "observed whiff proportion",
       x = "projected % whiff chance",
       title = "Fastball Whiff Model Prediction",
       subtitle = "Whiff proportion by predicted whiff value",
       caption = "Whiff predictions have a 1% bin width")
```