---
title: "Week 6"
author: "Evan Wu"
date: "`r Sys.Date()`"
output: html_document
---

<br>

##### Libraries

``` {r Libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(ggforce)
library(knitr)
library(forcats)
```

``` {r Data, echo = FALSE, message = FALSE, warning = FALSE}
data <- read_csv("pitch_arsenals_spin.csv")

stats_2022 <- read_csv("stats.csv")

speed_2022 <- read_csv("pitch_arsenals_mph.csv")
```

``` {r Pitcher Data, echo = FALSE, warning = FALSE, message = FALSE}
# Auto Reading Data
files <- list.files("Data")

pitchers <- read_csv(paste0("Data/", files[1]))

for(i in 2:length(files)) {
pitchers <- rbind(pitchers,
                  read_csv(paste0("Data/",files[i])))
}

add <- stats_2022 %>% 
  select(player_id, woba)

pitchers <- pitchers %>% 
  left_join(add, by = c("pitcher...8" = "player_id")) %>% 
  mutate(ID = case_when(woba > 0.330 ~ "Bad",
                        woba < 0.280 ~ "Great",
                        TRUE ~ "Decent"),
         win_exp_added = case_when(inning_topbot == "Bot"  ~ -delta_home_win_exp,
                             inning_topbot == "Top"  ~ delta_home_win_exp),
         run_exp_added = -delta_run_exp,
         ra_on_play = post_bat_score - bat_score) %>% 
  rename(player_id = pitcher...8,
         hitter = stand,
         pitch_speed = release_speed)

pitchers <- pitchers %>% 
  select(ID, player_name, player_id, game_date, pitch_type, pitch_name,
         pitch_speed, spin_axis, pfx_x:plate_z, ra_on_play,
         release_pos_x, release_pos_z, bb_type:strikes, pitch_number,
         hitter, home_team:type, outs_when_up, inning, ra_on_play,
         run_exp_added, win_exp_added,
         sz_top, sz_bot, hit_distance_sc:release_extension,
         estimated_ba_using_speedangle:woba_value, at_bat_number)

pitchers <- pitchers %>% 
  mutate(pitch_name = str_replace(pitch_name, "4-Seam Fastball", "4-Seam")) 
```

``` {r Functions, echo = FALSE}
# Geom Zone (Jackie's) ####

geom_zone <- function(top = 11/3, bottom = 3/2, linecolor = "black"){
  geom_rect(xmin = -.7083, xmax = .7083, ymin = bottom, ymax = top,
            alpha = 0, color = linecolor, linewidth = 0.75)
}

# c(0, 0, -.25, -.5, -.25))

geom_plate <- function(pov = "pitcher"){
   df <- case_when(
     pov == "pitcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, .25, .5, .25)),
     pov == "catcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, -.25, -.5, -.25))
   )
  
   g <- geom_polygon(data = df, aes(x = x, y = y), fill = "white", color = "black", linewidth = 1.25)
  g
}
```

```{r Pitcher Prototypes, echo = FALSE}

comps_2022 <- stats_2022 %>% 
  left_join(speed_2022, c("player_id" = "pitcher")) %>% 
  select(first_name.x, last_name.x, player_id, woba, ff_avg_speed) %>% 
  rename(first_name = first_name.x,
         last_name = last_name.x,
         FF_speed = ff_avg_speed) %>% 
  arrange(woba)

# Finding Quantile Values

p10 <- quantile(comps_2022$woba, probs = 0.9)
p50 <- quantile(comps_2022$woba, probs = 0.5)
p90 <- quantile(comps_2022$woba, probs = 0.1)

pitchers_10 <- comps_2022 %>% 
  filter(woba > p10 - 0.010 & woba < p10 + 0.010,
         FF_speed > 93 & FF_speed < 95) %>% 
  mutate(ID = "Bad")

pitchers_50 <- comps_2022 %>% 
  filter(woba > p50 - 0.010 & woba < p50 + 0.010,
         FF_speed > 93 & FF_speed < 95) %>% 
  mutate(ID = "Decent")

pitchers_90 <- comps_2022 %>% 
  filter(woba > p90 - 0.010 & woba < p90 + 0.010,
         FF_speed > 93.5 & FF_speed < 94.5) %>% 
  mutate(ID = "Great")

# Making Comps

candidates <- rbind(pitchers_10, pitchers_50, pitchers_90) 

sample <- candidates %>% 
  filter(player_id %in% c("641745", "621244", "680686",
                          "677651", "641154", "592791",
                          "668678", "453286", "666201"))

sample %>% 
  mutate(Name = paste(first_name, last_name)) %>% 
  select(ID, Name, player_id, woba, FF_speed) %>% 
  rename(wOBA = woba,
         MPH = FF_speed,
         Group = ID,
         P_ID = player_id) %>% 
  kable()

sample %>% 
  ggplot(aes(x = FF_speed, y = woba, color = ID)) +
  geom_point() +
  geom_label(label = sample$last_name, size = 1.25) +
  xlim(92, 98) +
  labs(x = "Four-Seam Fastball Average Speed (mph)",
       y = "2022 Opponent wOBA",
       color = "Group")

```

```{r Exporing Pitchers Data, echo = FALSE, warning = FALSE, message = FALSE}


pitchers %>% 
  filter(player_id == "641154") %>% 
  ggplot(aes(x = -pfx_x*12, y = pfx_z*12)) +
  geom_vline(xintercept = 0, linewidth = 0.5) +
  geom_hline(yintercept = 0, linewidth= 0.5) +
  geom_point(aes(color = pitch_name), alpha = 0.35, shape = 18, size = 2) + 
  coord_fixed() +
  labs(x = "Induced Horizontal Movement",
       y = "Induced Vertical Movement",
       color = "Pitch",
       shape = "Pitch",
       title = "Pablo Lopez",
       subtitle = "2022 Season",
       caption = "Data from Baseball Savant") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5))

pitchers %>% 
  filter(player_id == "641154",
         pitch_name == "Sinker") %>% 
  ggplot(aes(x = -plate_x, y = plate_z)) +
  geom_zone() +
  geom_plate() +
  geom_vline(xintercept = 0, linewidth = 0.5) +
  geom_hline(yintercept = 0, linewidth= 0.5) +
  geom_point(alpha = 0.65, shape = 18, size = 2.5) + 
  coord_fixed() +
  labs(color = "Pitch",
       shape = "Pitch",
       title = "Pablo Lopez's Sinkers",
       subtitle = "2022 Season",
       caption = "Data from Baseball Savant") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5))


pitchers %>% 
  filter(player_id == "666201") %>% 
  ggplot(aes(x = -pfx_x*12, y = pfx_z*12)) +
  geom_vline(xintercept = 0, linewidth = 0.5) +
  geom_hline(yintercept = 0, linewidth= 0.5) +
  geom_point(aes(color = pitch_name), alpha = 0.35, shape = 18, size = 2) + 
  coord_fixed() +
  labs(x = "Induced Horizontal Movement",
       y = "Induced Vertical Movement",
       color = "Pitch",
       shape = "Pitch",
       title = "Alek Manoah",
       subtitle = "2022 Season",
       caption = "Data from Baseball Savant") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5))

```

```{r Pitcher Comps, echo = FALSE, warning = FALSE, message = FALSE}

pitchers %>% 
  filter(pitch_type == "FF") %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = "", y = release_spin_rate)) +
  geom_jitter(aes(color = ID), width = 0.25, height = 0, alpha = 0.25) +
  facet_wrap(~ player_name) +
  labs(title = "Spin Rate of Four-Seams",
       x = "",
       y = "Spin Rate (rpm)") +
  NULL


pitchers %>% 
  filter(pitch_type == "FF") %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = -pfx_x*12, y = pfx_z*12)) +
  geom_jitter(aes(color = ID), width = 0.25, height = 0, alpha = 0.25) +
  facet_wrap(~ player_name) +
  labs(title = "Induced Movement of Four-Seams") +
  NULL


pitchers %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = -pfx_x*12, y = pfx_z*12)) +
  geom_jitter(aes(color = pitch_name), width = 0.25, height = 0, alpha = 0.25) +
  facet_wrap(~ player_name) +
  labs(title = "Induced Movement of Pitch Arsenal") +
  NULL

pitchers %>% 
  filter(pitch_type == "FF") %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = "", y = run_exp_added)) +
  geom_jitter(aes(color = ID), width = 0.25, height = 0, alpha = 0.25) +
  facet_wrap(~ player_name) +
  labs(title = "Change in Run Expectancy") +
  NULL

###########
pitchers %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = player_name, y = estimated_woba_using_speedangle)) +
  geom_boxplot(aes(fill = pitch_name)) +
  facet_grid(rows = vars(ID), scales = "free") +
  labs(title = "xwOBA") +
  NULL


avg <- pitchers %>% 
  select(player_name, player_id, ID, pitch_type, pitch_speed, pfx_x, pfx_z, 
         release_spin_rate, estimated_woba_using_speedangle) %>% 
  filter(!is.na(pitch_type)) %>% 
  group_by(player_name, pitch_type) %>% 
  summarize("speed" = mean(pitch_speed, na.rm = TRUE), 
            "_x" = mean(pfx_x, na.rm = TRUE),
            "_z" = mean(pfx_z, na.rm = TRUE), 
            "spin_rate" = mean(release_spin_rate, na.rm = TRUE),
            xwOBA = mean(estimated_woba_using_speedangle, na.rm = TRUE),
            Pitches = n()) %>% 
  as.data.frame()


delta_sl <- pitchers %>% 
  filter(pitch_type == "SL") %>% 
  left_join(avg, by = c("player_name", "pitch_type")) %>% 
  mutate(delta_speed = pitch_speed - speed,
         delta_mov_x = pfx_x - `_x`,
         delta_mov_z = pfx_x - `_z`,
         delta_spin = release_spin_rate - spin_rate) %>% 
  select(-speed:-spin_rate)

delta_sl %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = "", y = delta_speed)) +
  geom_boxplot(aes(fill = ID)) +
  geom_jitter(width = 0.075, height = 0, alpha = 0.075) +
  facet_wrap(~ player_name) +
  labs(title = "Speed Differential (Against Average) for Sliders") +
  NULL


delta_sl %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = "", y = abs(delta_speed))) +
  geom_boxplot(aes(fill = ID)) +
  geom_jitter(width = 0.075, height = 0, alpha = 0.075) +
  facet_wrap(~ ID+player_name) +
  labs(title = "Absolute Speed Differential (Against Average) for Sliders") +
  NULL



delta_all <- pitchers %>% 
  left_join(avg, by = c("player_name", "pitch_type")) %>% 
  mutate(delta_speed = pitch_speed - speed,
         delta_mov_x = pfx_x - `_x`,
         delta_mov_z = pfx_x - `_z`,
         delta_spin = release_spin_rate - spin_rate) %>% 
  select(-speed:-spin_rate) %>% 
aggregate(abs(delta_speed) ~ player_name + pitch_type, data = ., FUN = mean) %>% 
  mutate(ID = case_when(
    player_name  %in% c("Gallen, Zac", "Manoah, Alek", "Scherzer, Max") ~ "Great",
    player_name  %in% c("López, Pablo", "Garcia, Luis", "Taillon, Jameson") ~ "Decent",
    player_name  %in% c("Berríos, José", "Gray, Josiah", "Keller, Brad") ~ "Bad"
  ))

delta_all %>% 
  ggplot(aes(x = "", y = `abs(delta_speed)`, color = ID)) +
  geom_jitter(width = 0.25, show.legend = FALSE) +
  facet_wrap(~ ID)

delta_all %>% 
  ggplot(aes(x = "", y = `abs(delta_speed)`, color = pitch_type)) +
  geom_jitter(width = 0.25, show.legend = FALSE) +
  facet_wrap(~ ID)


pitchers %>% 
  filter(pitch_type == "FF") %>% 
  left_join(avg, by = c("player_name", "pitch_type")) %>% 
  mutate(delta_speed = pitch_speed - speed,
         delta_mov_x = pfx_x - `_x`,
         delta_mov_z = pfx_x - `_z`,
         delta_spin = release_spin_rate - spin_rate) %>% 
  mutate(player_name = fct_reorder(as.factor(player_name), ID, .desc = TRUE)) %>% 
  ggplot(aes(x = "", y = delta_speed, color = xwOBA)) +
  geom_boxplot(aes(fill = ID), color = "black") +
  geom_jitter(width = 0.075, height = 0, alpha = 0.075) +
  scale_color_gradient2(low = "green", midpoint = 0.41, high = "red") +
  facet_wrap(~ player_name) +
  labs(title = "Speed Differential (Against Average) for Sliders") +
  NULL
```

