---
title: "Week 7"
author: "Evan Wu"
date: "`r Sys.Date()`"
output: html_document
---

<br>

##### Libraries

``` {r Libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(ggforce)
library(knitr)
library(forcats)
library(olsrr)
library(ranger)
library(Metrics)

set.seed(3630)
```

``` {r Data, echo = FALSE, message = FALSE, warning = FALSE}
seasonal <- read_csv("CSVs/season_stats.csv")

pitchers <- read_csv("CSVs/pitcher_comps.csv")

arsenal <- read_csv("CSVs/arsenal.csv")
```

``` {r Functions, echo = FALSE}
# Geom Zone (Jackie's) ####

geom_zone <- function(top = 11/3, bottom = 3/2, linecolor = "black"){
  geom_rect(xmin = -.7083, xmax = .7083, ymin = bottom, ymax = top,
            alpha = 0, color = linecolor, linewidth = 0.75)
}

# c(0, 0, -.25, -.5, -.25))

geom_plate <- function(pov = "pitcher"){
   df <- case_when(
     pov == "pitcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, .25, .5, .25)),
     pov == "catcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, -.25, -.5, -.25))
   )
  
   g <- geom_polygon(data = df, aes(x = x, y = y), fill = "white", color = "black", linewidth = 1.25)
  g
}
```

```{r RHP Linear Model, echo = FALSE, warning = FALSE}
# Model Data (Pitch = Slider, Pitching Hand = Right)
model_data <- arsenal %>% 
  filter(pitch_type == "SL",
         pitch_hand == "R") %>% 
  mutate(ovr_break = sqrt(pitcher_break_x^2 + pitcher_break_z^2))

# Simple Linear Regression
lm_simple <- lm(xwOBA ~ 
     pitch_speed + spin_rate + pitcher_break_x + pitcher_break_z +
     pitch_usage + ovr_break,
  data = model_data)

summary(lm_simple)


# Overview of all model combinations
model_all <- ols_step_all_possible(lm_simple)

# Backwards Elimination
lm_simple %>% ols_step_backward_p(penter = 0.2)

# Stepwise Selection
lm_simple %>% ols_step_both_p(prem = 0.15, pent = 0.15)

# New Model
lm1 <- lm(xwOBA ~ 
     ovr_break + pitch_usage + pitch_speed,
  data = model_data)

lm1 %>% 
  summary()
```

```{r RHP Linear Model Interactions, echo = FALSE, warning = FALSE}
# Model Data (Pitch = Slider, Pitching Hand = Right)

# Interaction Linear Regression
lm_interact <- lm(xwOBA ~ 
      pitch_speed + spin_rate + pitcher_break_x + pitcher_break_z + pitch_usage + 
       ovr_break + 
       pitch_speed*spin_rate + pitch_speed*pitch_usage + pitch_speed*ovr_break +
       pitch_speed*pitcher_break_x + pitch_speed*pitcher_break_z + 
        spin_rate*ovr_break + spin_rate*pitcher_break_x + spin_rate*pitcher_break_z +
        pitch_usage*ovr_break + pitch_usage*spin_rate,
  data = model_data)

summary(lm_interact)


# model_interact_all <- ols_step_all_possible(lm_interact)

# Stepwise Selection
lm_interact %>% ols_step_both_p(pent = 0.15, prem = 0.05)

# Output removes ALL interactions for p < 0.05
# Keeps same as simple LM pitcher_break_z + pitch_speed + pitch_usage

lm_interact %>% ols_step_both_p(pent = 0.15, prem = 0.10)

# New Model with Interactions (p -value < 0.10 threshhold)
lm2 <- lm(xwOBA ~ 
     pitch_speed + pitch_usage + 
     pitch_speed*ovr_break + pitch_speed*pitcher_break_z,
  data = model_data)

lm2 %>% 
  summary()
```

```{r RHP LM Comparisons, echo = FALSE}
# Trimmed Data
model_results <- model_data %>% 
  select(first_name, last_name, 
         pitch_speed, pitch_usage, pitcher_break_z, ovr_break, xwOBA)
  
# Comparing Model Predictions
# lm1 = simple
# lm2 = interactions

model_results <- model_results %>% 
  mutate(lm1 = predict(lm1, model_results)) %>% 
  mutate(lm2 = predict(lm2, model_results))

# R and RMSE of Simple Linear Model
with(model_results, cor(xwOBA, lm1))
with(model_results, rmse(xwOBA, lm1))

# R and RMSE of Interactions Linear Model
with(model_results, cor(xwOBA, lm2))
with(model_results, rmse(xwOBA, lm2))

model_results %>% 
  select(xwOBA, lm1, lm2) %>%
  pivot_longer(cols = lm1:lm2, 
               names_to = "model",
               values_to = "pred") %>% 
  mutate(model = str_replace(model, "lm1", "Simple LM"),
         model = str_replace(model, "lm2", "Interaction LM")) %>%
  ggplot(aes(x = xwOBA, y = pred, color = model)) +
  geom_point(shape = 18, size = 1.5, alpha = 0.75) + 
  geom_smooth(se = FALSE) +
  scale_color_manual(values = c("navyblue", "skyblue")) +
  theme_classic() +
  labs(title = "Linear Models for RHP",
       x = "Observed",
       y = "Predicted",
       color = "Model")
```



```{r LHP Linear Model, echo = FALSE, warning = FALSE}
# Model Data (Pitch = Slider, Pitching Hand = Right)
model_data_l <- arsenal %>% 
  filter(pitch_type == "SL",
         pitch_hand == "L") %>% 
  mutate(ovr_break = sqrt(pitcher_break_x^2 + pitcher_break_z^2))

# Simple Linear Regression
lm_simple_l <- lm(xwOBA ~ 
     pitch_speed + spin_rate + pitcher_break_x + pitcher_break_z +
     pitch_usage + ovr_break,
  data = model_data_l)

summary(lm_simple_l)


# Overview of all model combinations
model_all_l <- ols_step_all_possible(lm_simple_l)

# Backwards Elimination
lm_simple_l %>% ols_step_backward_p(penter = 0.15)

# Stepwise Selection
lm_simple_l %>% ols_step_both_p(prem = 0.15, pent = 0.15)

# New Model
lm1_l <- lm(xwOBA ~ 
     pitcher_break_x + pitcher_break_z +
     ovr_break,
  data = model_data_l)

lm1_l %>% 
  summary()
```

```{r LHP Linear Model Interactions, echo = FALSE, warning = FALSE}
# Model Data (Pitch = Slider, Pitching Hand = Right)

# Interaction Linear Regression
lm_interact_l <- lm(xwOBA ~ 
      pitch_speed + spin_rate + pitcher_break_x + pitcher_break_z + pitch_usage + 
       ovr_break + 
       pitch_speed*spin_rate + pitch_speed*pitch_usage + pitch_speed*ovr_break +
       pitch_speed*pitcher_break_x + pitch_speed*pitcher_break_z + 
        spin_rate*ovr_break + spin_rate*pitcher_break_x + spin_rate*pitcher_break_z +
        pitch_usage*ovr_break + pitch_usage*spin_rate,
  data = model_data_l)

summary(lm_interact_l)


# model_interact_all <- ols_step_all_possible(lm_interact)

# Stepwise Selection
lm_interact_l %>% ols_step_both_p(pent = 0.15, prem = 0.05)

# Output removes ALL interactions for p < 0.05
# Keeps same as simple LM pitcher_break_z + pitch_speed + pitch_usage

lm_interact_l %>% ols_step_both_p(pent = 0.20, prem = 0.05)

# New Model with Interactions (p -value < 0.10 threshhold)
lm2_l <- lm(xwOBA ~ 
     spin_rate*pitcher_break_z,
  data = model_data_l)

lm2_l %>% 
  summary()
```

```{r LHP LM Comparisons, echo = FALSE}
# Trimmed Data
model_results_l <- model_data_l %>% 
  select(first_name, last_name, 
         pitch_speed, pitch_usage, pitcher_break_z, ovr_break, xwOBA)
  
# Comparing Model Predictions
# lm1 = simple
# lm2 = interactions

model_results_l <- model_results_l %>% 
  mutate(lm1 = predict(lm1, model_results_l)) %>% 
  mutate(lm2 = predict(lm2, model_results_l))

# R and RMSE of Simple Linear Model
with(model_results_l, cor(xwOBA, lm1))
with(model_results_l, rmse(xwOBA, lm1))

# R and RMSE of Interactions Linear Model
with(model_results_l, cor(xwOBA, lm2))
with(model_results_l, rmse(xwOBA, lm2))

model_results_l %>% 
  select(xwOBA, lm1, lm2) %>%
  pivot_longer(cols = lm1:lm2, 
               names_to = "model",
               values_to = "pred") %>% 
  mutate(model = str_replace(model, "lm1", "Simple LM"),
         model = str_replace(model, "lm2", "Interaction LM")) %>%
  ggplot(aes(x = xwOBA, y = pred, color = model)) +
  geom_point(shape = 18, size = 1.5, alpha = 0.75) + 
  geom_smooth(se = FALSE) +
  scale_color_manual(values = c("navyblue", "skyblue")) +
  theme_classic() +
  labs(title = "Linear Models for LHP",
       x = "Observed",
       y = "Predicted",
       color = "Model")
```


```{r Max Scherzer Linear Model, echo = FALSE, warning = FALSE}

# Model Data (Pitch = Slider)
scherzer <- pitchers %>% 
  filter(player_name  %in% "Scherzer, Max", 
         pitch_type == "SL") %>% 
  mutate(pfx_x = pfx_x*12,
         pfx_z = pfx_z*12,
         ovr_break = round(sqrt(pfx_x^2 + pfx_z^2), 3))

# Simple Linear Regression
lm_scherzer <- lm(run_exp_added ~ 
     pitch_speed + release_spin_rate + pfx_x + pfx_z +
     ovr_break,
  data = scherzer)

summary(lm_scherzer)


# Overview of all model combinations
model_all <- ols_step_all_possible(lm_scherzer)

# Stepwise Selection
lm_scherzer %>% ols_step_both_p(prem = 0.15, pent = 0.15)

# New Model
lm1_scherzer <- lm(run_exp_added ~ 
     pitch_speed,
  data = scherzer)

lm1_scherzer %>% 
  summary()
```

```{r Max Scherzer Linear Model Interactions, echo = FALSE, warning = FALSE}
# Model Data (Pitch = Slider)

# Interaction Linear Regression
lm_interact_scherzer <- lm(run_exp_added ~ 
      pitch_speed + release_spin_rate + pfx_x + pfx_z +
     ovr_break +
       pitch_speed*release_spin_rate + pitch_speed*pfx_x + pitch_speed*pfx_z +
       pitch_speed*ovr_break + release_spin_rate*pfx_x + release_spin_rate*pfx_z + 
       release_spin_rate*ovr_break,
  data = scherzer)

summary(lm_interact_scherzer)


# model_interact_all <- ols_step_all_possible(lm_interact)

# Stepwise Selection
lm_interact_scherzer %>% ols_step_both_p(pent = 0.15, prem = 0.05)

# Model has only pitch speed (same as lm1)
```

```{r Max Scherzer LM Comparisons, echo = FALSE}
# Comparing Model Predictions
# lm1 = simple
# lm2 = interactions available but not used

model_results_scherzer <- scherzer %>% 
  select(run_exp_added, pitch_speed, release_spin_rate, pfx_x, pfx_z,
     ovr_break) %>% 
  mutate(lm = predict(lm1_scherzer, scherzer))

# R and RMSE of Simple Linear Model
with(model_results_scherzer, cor(run_exp_added, lm))
with(model_results_scherzer, rmse(run_exp_added, lm))

model_results_scherzer %>% 
  select(run_exp_added, lm) %>%
  ggplot(aes(x = run_exp_added, y = lm)) +
  geom_point(shape = 18, size = 1.5, alpha = 0.75) + 
  geom_smooth(se = FALSE) +
  theme_classic() +
  labs(title = "Linear Model for Max Scherzer",
       x = "Observed",
       y = "Predicted",
       color = "Model")
```



```{r Sample Pitch Linear Model, echo = FALSE, warning = FALSE}

# Model Data (Pitch = Slider)
pitches <- pitchers %>% 
  filter(pitch_type == "SL") %>% 
  mutate(pfx_x = pfx_x*12,
         pfx_z = pfx_z*12,
         ovr_break = round(sqrt(pfx_x^2 + pfx_z^2), 3))

# Simple Linear Regression
lm_pitches <- lm(run_exp_added ~ 
     pitch_speed + release_spin_rate + pfx_x + pfx_z +
     ovr_break + release_extension,
  data = pitches)

summary(lm_pitches)


# Stepwise Selection
lm_pitches %>% ols_step_both_p(prem = 0.25, pent = 0.15)

# New Model
lm1_pitches <- lm(run_exp_added ~ 
     release_spin_rate + pfx_x + release_extension,
  data = pitches)

lm1_pitches %>% 
  summary()
```

```{r Sample Pitch Linear Model Interactions, echo = FALSE, warning = FALSE}
# Model Data (Pitch = Slider)

# Interaction Linear Regression
lm_interact_pitches <- lm(run_exp_added ~ 
      pitch_speed + release_spin_rate + pfx_x + pfx_z +
     ovr_break + release_extension +
       pitch_speed*release_spin_rate + pitch_speed*pfx_x + pitch_speed*pfx_z +
       pitch_speed*ovr_break + pitch_speed*release_extension + 
       release_spin_rate*pfx_x + release_spin_rate*pfx_z + 
       release_spin_rate*ovr_break + release_spin_rate*release_extension +
       release_extension*pfx_x + release_extension*pfx_z + release_extension*ovr_break,
  data = pitches)

summary(lm_interact_pitches)


# model_interact_all <- ols_step_all_possible(lm_interact)

# Stepwise Selection
lm_interact_pitches %>% ols_step_both_p(pent = 0.15, prem = 0.15)

lm2_pitches <- lm(run_exp_added ~ 
     release_spin_rate*pfx_x + release_extension,
  data = pitches)

lm2_pitches %>% 
  summary()
```

```{r Sample Pitch LM Comparisons, echo = FALSE}
# Comparing Model Predictions
# lm1 = simple
# lm2 = interactions available but not used

model_results_pitches <- pitches %>% 
  select(run_exp_added, pitch_speed, release_spin_rate, pfx_x, pfx_z,
         release_extension) %>% 
  mutate(lm1 = predict(lm1_pitches, pitches),
         lm2 = predict(lm2_pitches, pitches))

# R and RMSE of Simple Linear Model

model_results_pitches %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(cor(run_exp_added, lm1))

model_results_pitches %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(rmse(run_exp_added, lm1))

# R and RMSE of Interaction Linear Model
model_results_pitches %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(cor(run_exp_added, lm2))

model_results_pitches %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(rmse(run_exp_added, lm2))

# Graph
model_results_pitches %>% 
  select(run_exp_added, lm1, lm2) %>%
  pivot_longer(cols = lm1:lm2, 
               names_to = "model",
               values_to = "pred") %>% 
  mutate(model = str_replace(model, "lm1", "Simple LM"),
         model = str_replace(model, "lm2", "Interaction LM")) %>%
  ggplot(aes(x = run_exp_added, y = pred, color = model)) +
  geom_point(shape = 18, size = 1.5, alpha = 0.75) + 
  geom_smooth(se = FALSE) +
  scale_color_manual(values = c("navyblue", "skyblue")) +
  theme_classic() +
  labs(title = "Linear Models for Pitch-by-Pitch Data",
       subtitle = "Predicting Run Expectancy Added",
       caption = "Pitchers: Scherzer, Taillon, Keller, Manoah, Gallen, Garcia, Gray",
       x = "Observed",
       y = "Predicted",
       color = "Model")
```

```{r Sample Pitch Linear Model Investigation, echo = FALSE, warning = FALSE}
model_results_pitches_2 <- pitches %>% 
  select(run_exp_added, pitch_speed, release_spin_rate, pfx_x, pfx_z,
         release_extension, ID) %>% 
  mutate(lm1 = predict(lm1_pitches, pitches),
         lm2 = predict(lm2_pitches, pitches))

# Graph
model_results_pitches_2 %>% 
  select(ID,run_exp_added, lm1, lm2) %>%
  pivot_longer(cols = lm1:lm2, 
               names_to = "model",
               values_to = "pred") %>% 
  mutate(model = str_replace(model, "lm1", "Simple LM"),
         model = str_replace(model, "lm2", "Interaction LM")) %>%
  ggplot(aes(x = run_exp_added, y = pred, color = model)) +
  geom_point(shape = 18, size = 1.5, alpha = 0.75) + 
  geom_smooth(se = FALSE) +
  scale_color_manual(values = c("navyblue", "skyblue")) +
  facet_wrap(~ ID, ncol = 1) +
  theme_classic() +
  labs(title = "Linear Models for Pitch-by-Pitch Data",
       subtitle = "Predicting Run Expectancy Added",
       caption = "Pitchers: Scherzer, Taillon, Keller, Manoah, Gallen, Garcia, Gray",
       x = "Observed",
       y = "Predicted",
       color = "Model")

# Correlations

model_results_pitches_2 %>% 
  filter(ID == "Great") %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(cor(run_exp_added, lm1))

model_results_pitches_2 %>% 
  filter(ID == "Decent") %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(cor(run_exp_added, lm1))

model_results_pitches_2 %>% 
  filter(ID == "Bad") %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(cor(run_exp_added, lm1))


# RMSE

model_results_pitches_2 %>% 
  filter(ID == "Great") %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(rmse(run_exp_added, lm1))

model_results_pitches_2 %>% 
  filter(ID == "Decent") %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(rmse(run_exp_added, lm1))

model_results_pitches_2 %>% 
  filter(ID == "Bad") %>% 
  filter(!is.na(release_spin_rate),
         !is.na(pfx_x),
         !is.na(release_extension),
         !is.na(run_exp_added)) %>% 
  with(rmse(run_exp_added, lm1))
```

```{r}
pitchers %>% 
  # filter(pitch_type == "SL") %>%
  ggplot(aes(x = plate_z)) +
  geom_histogram(binwidth = 0.15, color = "white")

pitchers %>% 
  ggplot(aes(x = run_exp_added)) +
  geom_histogram(binwidth = 0.15, color = "white")

pitchers %>% 
  filter(pitch_type %in% c("FF", "SL", "CH")) %>%
  mutate(pitch_dist = sqrt(plate_x^2 + (2.5 - plate_z)^2)) %>% 
  ggplot(aes(x = pitch_dist, color = ID)) +
  geom_density() +
  facet_wrap(~ pitch_type,
             ncol = 1)

pitchers %>% 
  filter(pitch_type %in% c("FF", "SL", "CH")) %>%
  mutate(pitch_dist = sqrt(plate_x^2 + (2.5 - plate_z)^2)) %>%
  ggplot(aes(x = pitch_dist, y = run_exp_added)) +
  geom_point(alpha = 0.15)
```

```{r RHP_FF Linear Model, echo = FALSE, warning = FALSE}
# Model Data (Pitch = Slider, Pitching Hand = Right)
rhp_ff_data <- arsenal %>% 
  filter(pitch_type == "FF",
         pitch_hand == "R") %>% 
  mutate(ovr_break = sqrt(pitcher_break_x^2 + pitcher_break_z^2))

# Simple Linear Regression
lm_ff <- lm(xwOBA ~ 
     pitch_speed + spin_rate + pitcher_break_x + pitcher_break_z +
     pitch_usage + ovr_break,
  data = rhp_ff_data)

summary(lm_ff)


# Stepwise Selection
lm_ff %>% ols_step_both_p(prem = 0.15, pent = 0.15)

# New Model
lm1_ff <- lm(xwOBA ~ 
     spin_rate + pitcher_break_x*pitcher_break_z + pitch_speed,
  data = rhp_ff_data)

lm1_ff %>% 
  summary()

pitchers %>% 
  filter(pitch_type == "FF",
         !is.na(release_spin_rate),
         !is.na(pitch_speed)) %>% 
  with(cor(release_spin_rate, pitch_speed))

hi <- pitchers %>% 
  filter(pitch_type == "FF") %>% 
  mutate(pitch_dist = sqrt(plate_x^2 + (2.5 - plate_z)^2),
         pitch_dist_sq = pitch_dist^2)

lm(run_exp_added ~ pitch_dist_sq + pitch_dist + 
     release_spin_rate,
   data = hi) %>% 
  summary()

table(pitchers$pitch_name)
```