---
title: "Week 10"
author: "Evan Wu"
output: 
  html_document:
    code_folding:
      hide
---

<br>

#### Code Background

Looking at whiff data for right-handed pitchers (from 2022, 85 pitchers with
1842+ seasonal pitches). 

<br>

#### Libraries
```{r Libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
library(glmnet)
library(patchwork)
library(olsrr)
library(broom)
options(scipen = 999)
library(RColorBrewer)
library(Metrics)
```


``` {r Functions, }
# Geom Zone (Jackie's) ####

geom_zone <- function(top = 11/3, bottom = 3/2, linecolor = "black"){
  geom_rect(xmin = -.7083, xmax = .7083, ymin = bottom, ymax = top,
            alpha = 0, color = linecolor, linewidth = 0.75)
}

# c(0, 0, -.25, -.5, -.25))

geom_plate <- function(pov = "pitcher"){
   df <- case_when(
     pov == "pitcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, .25, .5, .25)),
     pov == "catcher" ~ 
       data.frame(x = c(-.7083, .7083, .7083 ,0, -.7083), y = c(0, 0, -.25, -.5, -.25))
   )
  
   g <- geom_polygon(data = df, aes(x = x, y = y), fill = "white", color = "black", linewidth = 1.25)
  g
}

# Barrel Function
is.barrel <- function(LA, EV){
  upper <- 1.11*EV - 78.89
  lower <- -EV + 124
  outcome <- (LA >= lower) & (LA <= upper) & (EV >= 98) & (LA >= 8) & (LA <= 50)
  outcome <- replace_na(outcome, FALSE)
  outcome
}

swap_names <- function(name) {
  parts <- strsplit(name, ", ")[[1]]
  if (length(parts) == 2) {
    return(paste(rev(parts), collapse = " "))
  } else {
    return(name)
  }
}

```

```{r}
# Data
model <- read_csv("models3.csv") %>% 
  select(-...1) %>% 
  filter(!(term  %in%  c("(Intercept)", "pred_bwhiff", "pred_bbarrel", "pred_bstrike")))

# Keeping and renaming zone with lowest p-value
model <- model %>% 
  filter(!(term %in% c("zone1", "zone2", "zone3", "zone4", "zone6", "zone7", "zone8",
                       "zone9", "zone11", "zone12", "zone13", "zone14") & 
             p.value > min(p.value[term %in% c("zone1", "zone2", "zone3", "zone4", 
                                               "zone6", "zone7", "zone8", "zone9", 
                                               "zone11", "zone12", "zone13", "zone14")]))) %>% 
  mutate(term = ifelse(term  %in% c("zone1", "zone2", "zone3", "zone4", "zone6", "zone7", "zone8",
                       "zone9", "zone11", "zone12", "zone13", "zone14"),
                "best_zone", term))
  
# Plot with Geom Tile
model %>% 
  mutate(log_pval = -log10(p.value)) %>% 
  ggplot(aes(x = Response, y = term,
             fill = log_pval)) +
  scale_fill_gradient2(low = "khaki1", high = "green", na.value = "blue") +
  geom_tile() +
  facet_wrap(~ Pitch,
             ncol = 2) +
  theme_dark()

```

